stbx25xx-objs = demux.o video.o audio.o
obj-$(CONFIG_DVB_STBx25xx) += stbx25xx.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/ -Idrivers/media/dvb/frontends/
EXTRA_CFLAGS += -Idrivers/media/common/tuners/
