dvb_stbx25xx-objs = stbx25xx.o stbx25xx_demux.o stbx25xx_video.o stbx25xx_audio.o stbx25xx_tuner.o
obj-$(CONFIG_DVB_STBx25xx) += dvb_stbx25xx.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/ -Idrivers/media/dvb/frontends/
EXTRA_CFLAGS += -Idrivers/media/common/tuners/
